version: "3.8"

networks:
    mynet:
        driver: bridge

services:
    nginx:
        image: nginx:alpine
        container_name: nginx
        restart: unless-stopped
        tty: true
        ports:
            - 8080:80
        volumes:
            - ./:/var/www/html
            - ./server/nginx/conf.d/:/etc/nginx/conf.d/
        depends_on:
            - php
            - database
        networks:
            - mynet

    php:
        build:
            context: .
            target: php
            args:
                - APP_ENV=${APP_ENV}
        environment:
            - APP_ENV=${APP_ENV}
            - CONTAINER_ROLE=app
        restart: unless-stopped
        working_dir: /var/www/html
        volumes:
            - ./:/var/www/html
        ports:
            - 9000:9000
        depends_on:
            - database
        networks:
            - mynet

    database:
        image: mysql:8.0
        container_name: database
        restart: unless-stopped
        tty: true
        ports:
            - 3306:3306
        environment:
            - MYSQL_DATABASE=${DB_DATABASE}
            - MYSQL_USER=${DB_USERNAME}
            - MYSQL_PASSWORD=${DB_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
        volumes:
            - mysqldata:/var/lib/mysql
        networks:
            - mynet

#Volumes
volumes:
    mysqldata:
        driver: local
